[package]
name = "sel4_cspace"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4_common = { git = "https://github.com/rel4team/sel4_common.git", branch = "mi_dev" }
riscv = { git = "https://gitee.com/rcore-os/riscv", features = ["inline-asm"] }